### PR TITLE
Fix for undefined variable $version

### PR DESCRIPTION
**Pull request by pascalpp**
Ref: https://github.com/broadly/broadly/issues/3305

### CODE REVIEW

**Comment by lucasefe** [comment]
@assaf merging (and I guess deploying) is being prevented by the workflow failure. 

`- SVN_PASSWORD secret does not exist`

How should we proceed?

**Comment by pascalpp** [comment]
Bump. @assaf do you know what we need to do to release this bug fix for the wordpress plugin?

**Comment by assaf** [comment]
It’s in 1Password

**Comment by pascalpp** [comment]
:tada:

**Pull request merged**
